---
title: "Laboratorio 1"
output: html_notebook
author: Diana Gutiérrez
---
1. Vectores y matrices

```{r}
#CREACION DE UN VECTOR POR ESTUDIANTE
s1 <- c(50.4, 62.3, 92.1, 77.6, TRUE)
s2 <- c(41.7, 87.9, 75.3, 72.4, FALSE)
s3 <- c(30.3, 67.8, 69.3, 71.2, FALSE)
s4 <- c(65.4, 85.1, 92.3, 96.8, TRUE)
s5 <- c(70.4, 88.2, 95.2, 90.7, TRUE)

#VECTOR DE ESTUDIANTES
students_vector <- c(S1, S2, S3, S4, S5)
```
```{r}
#CREACION DE LA MATRIZ 

students_matrix <- matrix(students_vector, nrow=5, byrow=TRUE)
students_matrix
```


2. Nombrado de una matriz
```{r}
#CREACION DE VECTORES DE NOMBRES DE COLUMNAS Y FILAS

name_students <- c("Lily Brown", "Davis Moore", "Susan Taylor", "Mike Jones","Tom Hill")

name_courses_legal_age <- c("TIC", "Accounting", "Psychology", "Ethics",
"Legal_age")

#ASIGNACIÓN DE NOMBRES
rownames(students_matrix) <- name_students
colnames(students_matrix) <- name_courses_legal_age
students_matrix

```
3. rowSums, cbind
```{r}
total_grade_student <- rowSums(students_matrix[2:5,])
total_grade_student

result_students <- cbind(students_matrix, total_grade_student)
##
result_students
```
4. Seleccionando elementos
```{r}
#SELECCION DE ELEMENTOS INDICADOS
selected_elements <- result_students[c(1,3,5),c(2,4)]
selected_elements
```
5. Data frames
```{r}
#CREACION DE DATA FRAME DE NOTAS DE ESTUDIANTES
students_grades_df <- data.frame(result_students)
students_grades_df

#SELECCION DE CURSO Y EDAD, DEBEN CUMPLIRSE AMBAS CONDICIONES
new_students_grades <- subset(students_grades_df, Accounting > 80 & Legal_age == 1, select = c(Accounting, Legal_age))

new_students_grades
```
6. Funciones, Condicionale y Bucles
```{r}
students_projection <- function(matriz){
  for(i in 1:nrow(matriz)){ #recorre filas
    columns <- ncol(matriz)-2
    for(j in 1:columns){ #recorre columnas
      current <- matriz[i,j]
      print(current) #impresión de cada valor cuando se recorre la matriz
      #CONDICIONS DE APROBACION
      if(current <= 45){
        print("---Student at risk---")
      }else if(current> 45 & current < 61){
        print("...Student may be approved...")
      }else{
        print("***Student approved***")
      }
     
    }
  }
}

students_projection(result_students)
  
```
7. Data frames y lapply

```{r}
index_education <- function(grade){
  grade <- ((grade/100)+1)/2
  print(grade)
}

all_students_grade <- students_grades_df[ ,1:4]
all_students_grade
```
```{r}
students_index <- data.frame(lapply(all_students_grade, index_education))
students_index
```
8. Math utilities
```{r}
score_mean <- lapply(students_grades_df[ ,1:4], mean)
score_mean <- data.frame(score_mean)
score_mean
```


